### ISSUE TITLE
'pip install .' is failing

### ISSUE THREAD

**Issue by mahtDFR** [abey79/vsketch#119]
I've tried using Windows and Ubuntu to try and install this and feel like I'm banging my head against a brick wall, so would appreciate any hints.

The instructions seem to be written for Linux users since commands in Windows differ slightly. When installing via Windows it takes a ridiculously long time to collect dependencies (24 hours +) and then fails. Here's a sample snippet of the output I'm getting:

```
INFO: pip is looking at multiple versions of toml to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of text-unidecode to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pywinpty to determine which version is compatible with other requirements. This could take a while.
  Using cached pywinpty-0.5.tar.gz (50.8 MB)
Collecting terminado>=0.8.3
  Using cached terminado-0.9.4-py3-none-any.whl (14 kB)
Collecting pywinpty>=0.5
  Using cached pywinpty-1.0.1-cp39-none-win_amd64.whl (1.4 MB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
```

Under Ubuntu, I can't progress to try the examples. I've followed the [installation instructions](https://github.com/abey79/vsketch/tree/dependabot/pip/black-21.5b2#installing-and-running-the-examples) using a virtual environment. Here's the output I get:

```
$ git clone https://github.com/abey79/vsketch
Cloning into 'vsketch'...
remote: Enumerating objects: 818, done.
remote: Counting objects: 100% (92/92), done.
remote: Compressing objects: 100% (85/85), done.
remote: Total 818 (delta 30), reused 13 (delta 6), pack-reused 726
Receiving objects: 100% (818/818), 15.11 MiB | 2.34 MiB/s, done.
Resolving deltas: 100% (422/422), done.
$ cd vsketch
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install .
Directory '.' is not installable. File 'setup.py' not found.
```

[Installing via pip](https://vsketch.readthedocs.io/en/latest/install.html#installing-vsketch) gives me this output:

```
$ pip install git+https://github.com/abey79/vsketch#egg=vsketch
Collecting vsketch from git+https://github.com/abey79/vsketch#egg=vsketch
  Cloning https://github.com/abey79/vsketch to /tmp/pip-build-d1NJgc/vsketch
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-d1NJgc/vsketch/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d1NJgc/vsketch/

```

Where am I going wrong here?
Thanks in advance.

**Comment by abey79** [comment]
This might be due to the same Click 8 / Typer issue as #118. I will look into it ASAP.

**Comment by abey79** [comment]
You may check if `pip install -U git+https://github.com/abey79/vsketch@fix-no-typer#egg=vsketch` fixes the issue.

**Comment by yanndepps** [comment]
Had the same issues, but it's now working fine ! thanks a lot for the fixes.

**Comment by mahtDFR** [comment]
Running ```pip install -U git+https://github.com/abey79/vsketch@fix-no-typer#egg=vsketch``` worked for me too! Thanks, will close this now.

**Comment by ingorichter** [comment]
I had to remove `@fix-no-typer` to install on macOS. But it worked! Thanks

**Comment by abey79** [comment]
> I had to remove `@fix-no-typer` to install on macOS. But it worked! Thanks

Yes, I have merged this branch today so now the master is OK.

**Comment by mariana-s-fernandes** [comment]
I have tried all of the above in WSL today without any success :/
