### ISSUE TITLE
installation issues on MacOs Big Sur 11.5 

### ISSUE THREAD

**Issue by vikas1188** [abey79/vsketch#141]
I'm facing this issue with vpype

`ERROR: Could not find a version that satisfies the requirement vpype[all]==1.7.0 (from vsketch) (from versions: 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.4.0, 1.5.0, 1.5.1)
ERROR: No matching distribution found for vpype[all]==1.7.0`

I can't seem to move forward with the installation.

I really want to try all these generative art examples. Help me with this please.

**Comment by vikas1188** [comment]
It got resolved. If someone is doing it on MacOS Big Sur 11.5, ensure that you've python 3.9 installed on the host machine. Otherwise numpy or bezier will keep giving you issue.

Once you create your venv (virtual environment), please check the python version in that environment by `python --version` This shall ensure that your venv is created with correct python version

**Comment by abey79** [comment]
That's right, python 3.9 is required for Big Sur and/or M1. I further strongly suggest using MacPort to install python and required libraires.
