### ISSUE TITLE
Can't import import vsketch in google colab

### ISSUE THREAD

**Issue by chuongmep** [abey79/vsketch#163]
Hi abey79,
I have a problem when import vsketch, any solution for that? 
Thanks so much.
![image](https://user-images.githubusercontent.com/31106432/137078372-830e126d-2743-4d41-8f25-dcf0c56db72a.png)
File Sample : https://colab.research.google.com/drive/1fQKIrnbOBzhxeajDA0O6RFtb2n3crvN6?usp=sharing

**Comment by NicklasXYZ** [comment]
> @chuongmep take a look on this, https://colab.research.google.com/github/abey79/vsketch/blob/master/examples/_notebooks/google_colab.ipynb#scrollTo=fie8YrVfRT-U

Making sure all cells in the notebook are it run, then it works for me with not problems.
