### ISSUE TITLE
MacOs Issue

### ISSUE THREAD

**Issue by andeecollard** [abey79/vsketch#171]
Hi,
vsketch looks amazing but I can't get it to work on my Mac running 10.15

vsketch launches but the window on the left is blank and when I scroll down it says: Error: See Console.

In terminal: 
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>

I've tried various ways of updating the certificate, but I don't really know what I'm doing. Any specific instructions would be really helpful.

Well done on all your projects– you're a genius!

**Comment by andeecollard** [comment]
Got it working. Python installation is challenging!

**Comment by abey79** [comment]
Glad you worked it out. I'll close the issue, don't hesitate to re-open if you have further troubles.
