### ISSUE TITLE
Sketches can't import modules next to the sketch script

### ISSUE THREAD

**Issue by abey79** [abey79/vsketch#177]
Example:
```
demo
-> sketch_demo.py
-> utils.py
```
Then `sketch_demo.py` cannot `import utils`.

To address this, the sketch directory should be added to the python path by the sketch runner.

Workaround:
```python
import sys
from pathlib import Path

import vsketch

sys.path.append(str(Path(__file__).parent))

from utils import my_util

# ...
```

**Comment by peregrinogris** [comment]
I was having this issue, and one workaround I found was to run vsk adding the current directory to the `PYTHONPATH`:

```
PYTHONPATH=. vsk run
```
But yes, I'd love if this worked out of the box!
