### ISSUE TITLE
Installation error exit status 1: bezier problem

### ISSUE THREAD

**Issue by HannimalCrackers** [abey79/vsketch#182]
Trying to install on a Macbook and getting a long error with exit status 1, that "The BEZIER_INSTALL_PREFIX environment variable must be set."  Anyone know a workaround?

**Comment by abey79** [comment]
@HannimalCrackers Yes this is due to `bezier` not having a binary distribution for arm64 Macs yet (see https://github.com/dhermes/bezier/issues/276). The workaround is as follows:

```
BEZIER_NO_EXTENSION=true pip install git+https://github.com/abey79/vsketch#egg=vsketch
```

**Comment by HannimalCrackers** [comment]
This did not resolve the issue, but thank you for trying.
