### ISSUE TITLE
Qt issue

### ISSUE THREAD

**Issue by jamescarruthers** [abey79/vsketch#213]
When running a sketch on my M1 mac I get this:

Running sketch: /Users/james/Dropbox/Apps/vsketch/newSketch/sketch_newsketch.py
qt.qpa.window: <QNSWindow: 0x1293234c0; contentView=<QNSView: 0x129322a00; QCocoaWindow(0x600000770c60, window=QWidgetWindow(0x600001476f40, name="QGLWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
qt.qpa.window: <QNSWindow: 0x11ef230c0; contentView=<QNSView: 0x129322a00; QCocoaWindow(0x600000770c60, window=QWidgetWindow(0x600001476f40, name="QGLWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
qt.qpa.window: <QNSWindow: 0x129338df0; contentView=<QNSView: 0x1293389e0; QCocoaWindow(0x600000771130, window=QWidgetWindow(0x600001440060, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.

**Comment by abey79** [comment]
Yes, I get the same error. They are mostly harmless from what I can say. I'm not sure how to resolve them. They will likely disappear when I make the transition to PySide6.
