### ISSUE TITLE
Cant plot german "Umlaute"

### ISSUE THREAD

**Issue by spindla** [abey79/vsketch#215]
Hey,

i try to plot some postcards with your postcard example but i have the problem, that i cant plot characters like ß, ä, ü, ö.
Is there any way to do that?

spindla

**Comment by abey79** [comment]
Yes, this is a limitation of the stroke fonts I integrated in vpype, which only have the lower range of ASCI characters. Unfortunately, "complete" stroke fonts are relatively hard to come by and there is much to improve in this area.

**Comment by spindla** [comment]
Okay, thank you for this info!
I hope german postservice can understand the ss in Straße (street).

**Comment by abey79** [comment]
That will be fine. You can even abbreviate to "Str." (I've done that myself).
