### ISSUE TITLE
Feature Request: Easier Text in Vsketches

### ISSUE THREAD

**Issue by lenary** [abey79/vsketch#229]
I've been working with and really enjoying vsketch. Thank you for your hard work on it!

One thing I've run into is that I want to include text in some of my sketches, and as far as I can tell, the easiest way is to use your "hack" from your postcards sketch. I've been using the following (because I use `pushMatrix` a lot), but it would be nice to have this wrapped up nicely for use directly on the Vsketch object:
```python
    @staticmethod
    def text(vsk: vsketch.Vsketch, x, y, text, text_size, font):
        stroke_layer = vsk._cur_stroke if vsk._cur_stroke is not None else 1
        center = vsk._transform_line(np.array([complex(x, y)]))[0]
        vsk.vpype(
            f"text -l {stroke_layer} -s {text_size} -p {center.real} {center.imag} -a center -f {font} '{text}'"
        )
```

This feels pretty hacky, so I don't know if there's a nicer way of achieving the same using the vpype Python API.

**Comment by abey79** [comment]
Yes, this has long been on the todo list. I've been spending a lot of time with *vpype* lately, so *vsketch* didn't get as much love I would like to.

The proper way to implement this would be to use the [`vpype.text_line()`](https://vpype.readthedocs.io/en/latest/api/vpype.html#vpype.text_line) or [`vpype.test_block()`](https://vpype.readthedocs.io/en/latest/api/vpype.html#vpype.text_block) API. As you suggest, the location of the text should always be subject to the transformation. Whether or not the current transform should be applied on the text itself should probably be a dedicated parameter. Sometimes you want to add a label somewhere, sometime the text is an integral part of the artwork.

Would you be willing to prepare a PR for this? If so we could further discuss the details of the API here.

**Comment by lenary** [comment]
Yep, happy to do a PR. Will start on it imminently.

**Comment by abey79** [comment]
I envision something like this:

```python
def text(
    txt: str,
    x: float = 0.0,
    y: float = 0.0,
    width: Optional[float] = None,
    size: float = 0.0,
    scale_text: bool = False,
    font: str = "futural",
    align: str = "left",
    line_spacing: float = 1.0,
    justify: bool = False
):
    ...
```

It would rely on `text_line()` if `width = None`, else `text_block()`.

**Comment by lenary** [comment]
Ah, that's probably a simpler approach than mine. I was going to go with something like:
```python
def textMode(self, mode: str) -> None:
    ...
def textFont(self, font: str) -> None:
    ...
def textSize(self, size: float) -> None:
    ...
def textLine(self, text: str, x: float, y: float, align: str = "center", mode: Optional[str] = None) -> None:
    ...
# Hadn't quite got here yet
def textBlock(...):
    ...
```

Where the `mode` chooses between "label" which just translates the location, and "transform", which applies the whole transformation matrix.

I think yours is clearer for the main text API, and I won't delete all the contextual functions yet.

**Comment by abey79** [comment]
It's true that your approach is closer to the Processing API, which vsketch kind of attempts to emulate. I'm always stretched between trying to be faithful to Processing, or to do the more "pythonic" thing. Your approach requires quite a bit of state though, which is OK, but I'd factor all this in a helper class in a separate `text.py` file. `vsketch.py` is already way too long for my taste :)

**Comment by lenary** [comment]
I'll get an initial version up, later we can clear up and split some of the stuff in vsketch.py, especially as I would love to have push/pop for more attributes.
