### ISSUE TITLE
Closing the UI does not stop vsk process

### ISSUE THREAD

**Issue by burk** [abey79/vsketch#238]
Hey! Testing out the vsketch examples and I'm not able to exit without doing `kill <pid>`. Using the X in the UI closes the UI but the vsk process is still running. Is this expected?

Here's a dump of what py-spy thinks is going on after I've closed the UI.
```
Process 18062: /home/burk/dev/plotting/venv3/bin/python /home/burk/dev/plotting/venv3/bin/vsk run examples/random_lines
Python v3.9.12 (/usr/bin/python3.9)

Thread 18062 (idle): "MainThread"
    _shutdown (threading.py:1470)
Thread 18082 (idle): "AnyIO worker thread"
    wait (threading.py:312)
    get (queue.py:171)
    run (anyio/_backends/_asyncio.py:744)
    _bootstrap_inner (threading.py:973)
    _bootstrap (threading.py:930)
```

**Comment by abey79** [comment]
Yeah I noticed that too. It must be a recent change – I'll take a closer look tomorrow.

**Comment by burk** [comment]
I did a git bisect and it identified this commit 6f8ec4e7b54ac296bd4c4a52deee2df54e2921b6.

**Comment by abey79** [comment]
A likely culprit is watchfiles.

**Comment by burk** [comment]
Attempt at fix: https://github.com/abey79/vsketch/pull/239
