### ISSUE TITLE
vsketch not running on Google Colab

### ISSUE THREAD

**Issue by Vamoss** [abey79/vsketch#244]
The [given example](https://colab.research.google.com/github/abey79/vsketch/blob/master/examples/_notebooks/google_colab.ipynb#scrollTo=fie8YrVfRT-U) shows this error when trying to install the lib:
`ERROR: Package 'vsketch' requires a different Python: 3.7.13 not in '<3.11,>=3.8'`

Thanks

**Comment by abey79** [comment]
Running on colab is no longer supported (the doc still needs to be updated to reflect this). It *may* work, but will likely require additional setup. In any case, vsketch and vpype now require Python 3.8 or later.

**Comment by rcsmit** [comment]
> Running on colab is no longer supported (the doc still needs to be updated to reflect this). It _may_ work, but will likely require additional setup. In any case, vsketch and vpype now require Python 3.8 or later.

But not 3.10... So 3,8 or 3.9

**Comment by abey79** [comment]
@rcsmit Both vsketch and vpype (as of 1.10) support 3.10 now.
