### ISSUE TITLE
Feature request: blend mode in draw

### ISSUE THREAD

**Issue by mariana-s-fernandes** [abey79/vsketch#245]
Not sure if possible to implement in Python but I would be nice to have the option for the blend mode (as in Inkscape or Processing), so that when I plot different layers overlapping, the colors would blend.
For example, for plotting I always use the multiply mode to have a better idea of how the colors will mix.

**Comment by abey79** [comment]
Well that would require quite the extensive rewrite of the vpype viewer, which would be complicated by the fact that it's HW accelerated. Not saying it's impossible (I believe the way would be to render each layer to a texture, then render all textures on screen with a blend function), but sufficiently complex that I don't see myself giving it a try in the foreseeable future.

**Comment by mariana-s-fernandes** [comment]
Ok, totally understand. Thanks for answering! I was not aware of how complex this could be, but probably not worth the effort. It was just a nice to have. I always open the svg on Inkscape to plot anyways.
