### ISSUE TITLE
README.md has older, pip-based install instructions

### ISSUE THREAD

**Issue by e28eta** [abey79/vsketch#250]
New user here, and after installing [vpype](https://github.com/abey79/vpype) via `pipx`, I was confused by the "Installing" section of the [vsketch/README.md](https://github.com/abey79/vsketch/blob/master/README.md#installing-and-running-the-examples), which uses a `venv` and `pip install`

I did find [vsketch/docs/install.rst](https://github.com/abey79/vsketch/blob/master/docs/install.rst) and followed those instructions instead, which I think has me in a good spot.

However, I _think_ you should update the README? I don't know for sure, because I'm not sure what the replacement for the "run the examples" command would be. Maybe clone the repo independently of install? Or are they put somewhere accessible by `pipx`?

I'm an experienced developer, but fairly new to python, venvs, pipx, and now vpype.

Thanks for the work you've done on these packages, they look really exciting.

**Comment by abey79** [comment]
Yes, vsketch documentation/readme -- and in particular the installation instructions -- are currently in a dire state. I hope to improve it ASAP.
