### ISSUE TITLE
Ubuntu: document QT5 install

### ISSUE THREAD

**Issue by NelsonMinar** [abey79/vsketch#292]
This is a suggestion to update the docs to help people getting vsketch up and going. I've recently tried setting up vsketch on two different Ubuntu systems and get the following error when I run it:

```
$ vsk run master/examples/schotter
Running sketch: /home/nelson/src/vsketch/master/examples/schotter/sketch_schotter.py
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

Confusing error but it turns out the problem on both systems was that the Qt environment wasn't installed at all and needs to be installed in Ubuntu before any Python code can use it.

On a WSL Ubuntu 20.04 system running `apt install qt5-default` was all I had to do to install all the Qt stuff that vsketch relies on. This is the method recommended in [Qt's own docs](https://wiki.qt.io/Install_Qt_5_on_Ubuntu).

On a native Ubuntu 22.04 system there is no qt5-default package anymore. The [solution](https://askubuntu.com/questions/1335184/qt5-default-not-in-ubuntu-21-04) that worked for me was to run `apt install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools`

A simple thing in the end but it took me awhile to figure out what that opaque error meant!

**Comment by abey79** [comment]
With the migration to PySide6 (#319), vsketch now relies on Qt6. Hopefully this will solve this issue.
