### ISSUE TITLE
Add support for hpgl export

### ISSUE THREAD

**Issue by abey79** [abey79/vsketch#32]
Now that vpype has hpgl export, vsketch should support it.

**Comment by behrad-ahmadpour** [comment]
Hi 
i can work on?
it would be great to tell me more about this issue

**Comment by abey79** [comment]
`Vsketch.save()` currently always generate SVG (using `vp.write_svg()`). The goal would be to support HPGL export as well, using `vp.write_hpgl()`. The way I see things would be:
- add a new `format` parameter (default to None)
- attempt to infer desired format from file extension (if available, raise error otherwise)
- add tests to validate that the generated output is indeed in the expected format
- update the documentation and/or examples
