### ISSUE TITLE
Installation fails, but have correct Python version installed

### ISSUE THREAD

**Issue by thomasnicolet** [abey79/vsketch#414]
Running: `pipx install vsketch`

I get `Some possibly relevant errors from pip install:
    ERROR: Ignored the following versions that require a different python version: 1.0.0 Requires-Python >=3.9,<3.12; 1.0.0a0 Requires-Python >=3.9,<3.12; 1.0.0a1 Requires-Python >=3.9,<3.12
    ERROR: Could not find a version that satisfies the requirement vsketch (from versions: none)
    ERROR: No matching distribution found for vsketch`
    
    My `Python --version` outputs 3.9.18 (in a fresh conda env I just made, since I got the error message above with Python 3.8).
    
    Am I doing something wrong, is there a hidden dependency, or is it a bug?

**Comment by abey79** [comment]
It may very be that `pipx` is using a different python interpreter than that 3.9.18 one. If you have Python 3.9 installed somewhere, the best course of action is to tell pipx to use _that_ interpreter explicitely:

```
pipx install vsketch --python /path/to/python
```

**Comment by thomasnicolet** [comment]
Thank you, likely had messed up python versions on path. Have mainly used conda envs for versioning Python, and I was in a conda env with correct version, which pipx does not pick up on. Downloaded new Python (3.11), added to Path in environment variables (Windows), moved to top of list. I then reinstalled pipx in powershell, then installed it with pipx install vsketch. vsk works in conda too now.
